### ISSUE TITLE
Failed install

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/nitter_ynh#11]
c.f. https://github.com/YunoHost/issues/issues/1835

https://paste.yunohost.org/raw/tizamemamo

Relevant error messages:

```
+ sudo -u nitter env PATH=/opt/yunohost/nitter/nim-installation/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin nimble build -d:release -y
Verifying dependencies for nitter@0.1.0
    Prompt: No local packages.json found, download it from internet? -> [forced yes]
Downloading Official package list
SIGILL: Illegal operation.
```

**Comment by meowIAmAUser** [comment]
Still not working:
https://paste.yunohost.org/raw/osinizused

And if downloading the official packages.json doesn't work, maybe try to include one in the script itself?

**Comment by yalh76** [comment]
should be ok with last version
