### ISSUE TITLE
Upgrade fails

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/nitter_ynh#26]
This is the log https://paste.yunohost.org/raw/zijelofoza

I mainly see this:
`2022-06-28 11:34:17,127: WARNING - sh: 0: getcwd() failed: No such file or directory`

**Comment by Jules-Bertholet** [comment]
Fixed with 4508d48f466a4f1aa9a1ec77deca56aad4d7d79f

**Comment by stemy2** [comment]
Nope !

https://paste.yunohost.org/raw/muforuqemi

**Comment by Jules-Bertholet** [comment]
There is a delay between when the fix was pushed to GitHub and when Yunohost will pick it up. If you want to get the fixed version immediately you will need to upgrade from the command line with `sudo yunohost app upgrade nitter -u https://github.com/YunoHost-Apps/nitter_ynh`

**Comment by stemy2** [comment]
It failed too, for the exact same reason.

**Comment by Jules-Bertholet** [comment]
@stemy2 please post new log

**Comment by stemy2** [comment]
https://paste.yunohost.org/raw/ivucatuquv
