### ISSUE TITLE
Install fails during compilation

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/nitter_ynh#6]
### Describe the bug

* Install fails during compilation

### Context
- Hardware: *VPS bought online*
- YunoHost version: *latest stable*
- I have access to my server: *Through SSH*
- Using, or trying to install package version/branch: *lastest master*

### Steps to reproduce

- `sudo yunohost app install nitter`

### Expected behavior

*Install the package

### Logs

Compilation takes a very long time (and the server is not responding anymore during a while). And there is this error while installing:
```
Warning: Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3 -O3 -fno-strict-aliasing -fno-ident   -I/opt/yunohost/nitter/nim-installation/lib -I/opt/yunohost/nitter/src -o /opt/yunohost/nitter/.cache/nim/nitter_r/@mnitter.nim.c.o /opt/yunohost/nitter/.cache/nim/nitter_r/@mnitter.nim.c' failed with exit code: 137
Warning: gcc: fatal error: Killed signal terminated program cc1
Warning: compilation terminated.
```

**Comment by Jules-Bertholet** [comment]
Can you post the full debug log?

**Comment by lapineige** [comment]
I just did, I was waiting for the full log as the app did remove itself.

The compilation is killed on the way… I suppose it's too resource intensive for the server ? (the load went up to 100…)

**Comment by lapineige** [comment]
I purged my RAM to clear about 1GB (out of 2) and emptied the swap, and it worked… Probably a memory limit, maybe compilation needs something like 1GB of free RAM.
