### ISSUE TITLE
Blank Page on Install via Web Admin

### ISSUE THREAD

**Issue by mrbenns** [YunoHost-Apps/nitter_ynh#9]
**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change_url...), you are on the right place!*
   - *Otherwise, the issue may be due to the app itself. Refer to its documentation or repository for help.*
   - *When in doubt, post here and we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

### Describe the bug

Unable to install Nitter as all I get is a blank section of the App Catalog

### Context

- Hardware: Yunohost Virtualbox running on Windows 10
- YunoHost version: 4.2.6.1
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: Tried via webadmin and using the github pull
### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app install the_app
    ```
- *If you used the webadmin, please perform the equivalent command from the CLI first.*
- *If the error occurs in your browser, explain what you did:*
   1. *Go to Applications*
   2. *Click on Search and enter Nitter and click Install*
   3. *See blank (image attached)*

### Logs

There is no error message, just a blank section 
https://ibb.co/KLfrgNL

**Comment by Jules-Bertholet** [comment]
You can always install Nitter from the command line: `sudo yunohost app install nitter`

**Comment by meowIAmAUser** [comment]
> You can always install Nitter from the command line: `sudo yunohost app install nitter`

The install fails using that

**Comment by Jules-Bertholet** [comment]
@dhuschde Logs?

**Comment by meowIAmAUser** [comment]
https://paste.yunohost.org/raw/jazohazoli

**Comment by Jules-Bertholet** [comment]
What is the architecture of your Windows machine? (32 bit or 64 bit)

**Comment by meowIAmAUser** [comment]
I use a regular Computer x64

**Comment by tomaytotomato** [comment]
I am having the same issue on a Debian instance. Blank screen on Firefox and Chromium

**Comment by meowIAmAUser** [comment]
And I tried it on Edge, Firefox and Chrome on PopOS, Ubuntu and Windows...

I don't think that it has anything to do with the Browser or OS

Bruce ***@***.***> schrieb am Fr., 23. Juli 2021, 14:59:

**Comment by meowIAmAUser** [comment]
Testing Branch doesn't work too. [Logs](https://paste.yunohost.org/raw/efeqopusuf)

**Comment by changemenemo** [comment]
Just my 2 cents. It s still happening on a up to date install

**Comment by dumprop** [comment]
I have same problem (ynh 4.2.8.3)

**Comment by dumprop** [comment]
> 
> 
> Just my 2 cents. It s still happening on a up to date install

Installing via terminal helps

**Comment by meowIAmAUser** [comment]
The Page now works on the newest YunoHost Version, but it still can't install

https://paste.yunohost.org/raw/osinizused

**Comment by yalh76** [comment]
should be ok with last version
